Story6/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
]

landing_page/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name = 'landing')
]

landing_page/models.py
from django.db import models

# Create your models here.
class input(models.Model):
    status_user = models.CharField(max_length=300, blank = False, verbose_name=u" ")
    waktu_user = models.DateTimeField(auto_now_add = True, null = True)

    def __str__(self):
        return self.status_user

landing_page/forms.py
from django import forms
from .models import input

class status_input(forms.Form):
    # class Meta:
    #     model = input
    #     fields = ['status_user']
    #     widgets = {
    #         'status_user' : forms.CharField(attrs={'placeholder' : 'Masukkan status anda','style' : 'border:0; width:100%'})
    #     }
    status_user = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Masukkan status anda',
        'type' : 'text',
        'maxlength' : '300',
        'required' : True,
        'style' : 'border:0; width:100%;text-align:center;background:black;color:white;',
        'label' : '',
    }))

landing_page/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import input

# Create your views here.
# def home(request):
#     return render(request, 'index.html')

def home(request):
    if request.method == "POST":
        form = status_input(request.POST)
        if (form.is_valid()):
            status = input()
            status.status_user = form.cleaned_data['status_user']
            status.save()
        return redirect('/')
    else:
        form = status_input()
        status = input.objects.all().order_by('-waktu_user')
        response = {'status' : status, 'form': form}
        return render(request, 'index.html', response)

landing_page/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.css' %}"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Rabialco's Website</title>
</head>
<style>
    ::-webkit-input-placeholder{
        color: white;
    }
    html{
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    }
</style>
<body style="background: black;">
    <header>
        <nav class="navbar text-black navbar-dark navbar-expand-md bg-black justify-content-between">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-nav">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse dual-nav w-50 order-1 order-md-0">
                    <ul class="nav navbar-nav mx-auto">
                        <li class="nav-item active">
                            <a class="nav-link pl-0" style="text-align: center;" href="/">
                                <h4>◉</h4>
                                <h6>R</h6>
                            <span class="sr-only">Home</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container" style="max-width: 70%; display: flex; justify-content: center; align-items: center; margin-top: 15%;">
            <div class="row-12">
                <div class="col" style="text-align: center;">
                    <h1 style="color: white;">
                        Halo, apa kabar?
                    </h1>
                </div>
                <form method="POST" class="col">
                    {% csrf_token %}
                    <input type="text" name="status_user" class="form-control" placeholder="Masukkan status anda" maxlength="300" required="" style="border:0; width:100%;text-align:center;background:black;color:white;" label="" id="id_status_user">
                    <div class="row mb-5">
                        <input type="Submit" name="button_input" class="btn btn-primary" value="Enter" style="margin-top : 2%;text-align: center;margin-right: auto; margin-left: auto;border-radius: 18px;">
                    </div>
                </form>
                <div class="col" style="color: white; margin: 0 auto 0 auto;text-align: center;overflow-y: scroll; max-height: 200px; ">
                    {% for i in status %}
                        <p>
                            {{ i.status_user }} - {{i.waktu_user}}
                        </p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <footer style="position: absolute; top: 95%; width: 100%;">
        <p style="color: white; text-align: center;">
            <i>
                Rabialco Argana © 2019
            </i>
        </p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
</body>
</html>